In [1]:
#Import packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#load data
dataset = pd.read_csv('./Advertising.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print(dataset.head())

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9


In [3]:
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)
print("X_train :",X_train)
print("X_test :",X_test)
print("y_train :",y_train)
print("y_test :",y_test)

X_train : [[ 36.9  38.6  65.6]
 [ 31.5  24.6   2.2]
 [142.9  29.3  12.6]
 [209.6  20.6  10.7]
 [215.4  23.6  57.6]
 [102.7  29.6   8.4]
 [  8.6   2.1   1. ]
 [ 16.9  43.7  89.4]
 [125.7  36.9  79.2]
 [104.6   5.7  34.4]
 [109.8  14.3  31.7]
 [229.5  32.3  74.2]
 [253.8  21.3  30. ]
 [184.9  21.   22. ]
 [ 44.7  25.8  20.6]
 [ 62.3  12.6  18.3]
 [292.9  28.3  43.2]
 [172.5  18.1  30.7]
 [202.5  22.3  31.6]
 [  7.3  28.1  41.4]
 [265.2   2.9  43. ]
 [197.6   3.5   5.9]
 [218.5   5.4  27.4]
 [147.3  23.9  19.1]
 [171.3  39.7  37.7]
 [217.7  33.5  59. ]
 [262.7  28.8  15.9]
 [163.5  36.8   7.4]
 [100.4   9.6   3.6]
 [ 76.3  27.5  16. ]
 [184.9  43.9   1.7]
 [134.3   4.9   9.3]
 [273.7  28.9  59.7]
 [296.4  36.3 100.9]
 [ 96.2  14.8  38.9]
 [109.8  47.8  51.4]
 [255.4  26.9   5.5]
 [204.1  32.9  46. ]
 [240.1  16.7  22.9]
 [193.7  35.4  75.6]
 [191.1  28.7  18.2]
 [ 89.7   9.9  35.7]
 [ 43.   25.9  20.5]
 [ 38.2   3.7  13.8]
 [ 13.1   0.4  25.6]
 [239.3  15.5  27.3]
 [ 17.2  45.9  69.3]
 [2

In [4]:
#Train model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [5]:
#do prediction
pred_result = model.predict(X_test)
print("Predicted sales :",pred_result)

Predicted sales : [10.05739563  7.4522807   7.0197076  24.08029725 12.01786259  6.53793858
 12.78286918 15.10974587 10.76974013 16.34357951 22.88297477  9.12924467
 10.46455672 15.48743552 11.58555633 12.17296914 18.76551502 10.78318566
 15.90515992 17.30651279 24.06692057  9.59834224 15.13512211 12.38591525
  5.71360885 15.24749314 12.29402334 20.9421167  13.40991558  9.04348832
 12.89239415 21.40272028 18.13802209 21.17320803  6.56974433  6.14114206
  7.89018394 13.01541434 14.68953791  6.18835143]
